import { z } from "zod";

const emailSchema = z
  .string()
  .trim()
  .toLowerCase()
  .email("Please enter a valid email address.")
  .max(320, "Email address is too long.");

const passwordSchema = z
  .string()
  .min(12, "Password must be at least 12 characters long.")
  .max(128, "Password must not exceed 128 characters.")
  .regex(
    /[a-z]/,
    "Password must contain at least one lowercase letter.",
  )
  .regex(
    /[A-Z]/,
    "Password must contain at least one uppercase letter.",
  )
  .regex(
    /[0-9]/,
    "Password must contain at least one number.",
  )
  .regex(
    /[^A-Za-z0-9]/,
    "Password must contain at least one special character.",
  );

const otpSchema = z
  .string()
  .trim()
  .regex(/^\d{6}$/, "OTP must be a 6-digit code.");

const nameSchema = z
  .string()
  .trim()
  .min(1, "This field is required.")
  .max(100, "This field must not exceed 100 characters.")
  .regex(
    /^[\p{L}\p{M}' -]+$/u,
    "This field contains invalid characters.",
  );

/**
 * User registration
 *
 * The role is intentionally NOT accepted here.
 * Privileged role assignment must happen server-side.
 */
export const registerSchema = z
  .object({
    email: emailSchema,

    firstName: nameSchema,

    lastName: nameSchema,
  })
  .strict();

/**
 * Login
 */
export const loginSchema = z
  .object({
    email: emailSchema,

    password: z
      .string()
      .min(1, "Password is required.")
      .max(128, "Password is too long."),
  })
  .strict();

/**
 * Email verification OTP
 */
export const verifyEmailOtpSchema = z
  .object({
    email: emailSchema,

    otp: otpSchema,
  })
  .strict();

/**
 * Request another email verification OTP.
 */
export const resendEmailVerificationSchema = z
  .object({
    email: emailSchema,
  })
  .strict();

/**
 * Forgot password.
 *
 * The service layer must always return a generic response
 * so that the existence of an account cannot be discovered.
 */
export const forgotPasswordSchema = z
  .object({
    email: emailSchema,
  })
  .strict();

/**
 * Verify password reset OTP.
 *
 * The email + OTP combination is used to authorize
 * creation of a short-lived password reset token.
 */
export const verifyPasswordResetOtpSchema = z
  .object({
    email: emailSchema,

    otp: otpSchema,
  })
  .strict();

/**
 * Reset password.
 *
 * The token must have been generated by the verified
 * password-reset OTP flow.
 */
export const resetPasswordSchema = z
  .object({
    token: z
      .string()
      .trim()
      .min(1, "Reset token is required.")
      .max(512, "Reset token is too long."),

    password: passwordSchema,

    confirmPassword: z
      .string()
      .min(1, "Please confirm your password.")
      .max(128, "Password is too long."),
  })
  .strict()
  .superRefine((data, ctx) => {
    if (data.password !== data.confirmPassword) {
      ctx.addIssue({
        code: "custom",
        path: ["confirmPassword"],
        message: "Passwords do not match.",
      });
    }
  });

/**
 * Change password for an authenticated user.
 */
export const changePasswordSchema = z
  .object({
    currentPassword: z
      .string()
      .min(1, "Current password is required.")
      .max(128, "Password is too long."),

    newPassword: passwordSchema,

    confirmPassword: z
      .string()
      .min(1, "Please confirm your password.")
      .max(128, "Password is too long."),
  })
  .strict()
  .superRefine((data, ctx) => {
    if (data.currentPassword === data.newPassword) {
      ctx.addIssue({
        code: "custom",
        path: ["newPassword"],
        message:
          "New password must be different from the current password.",
      });
    }

    if (data.newPassword !== data.confirmPassword) {
      ctx.addIssue({
        code: "custom",
        path: ["confirmPassword"],
        message: "Passwords do not match.",
      });
    }
  });

/**
 * Login verification OTP.
 *
 * This is reserved for the later MFA/login-verification flow.
 */
export const verifyLoginOtpSchema = z
  .object({
    otp: otpSchema,
  })
  .strict();

/**
 * Generic OTP verification schema.
 *
 * Useful for service-level flows where the purpose has
 * already been established by the endpoint.
 */
export const verifyOtpSchema = z
  .object({
    otp: otpSchema,
  })
  .strict();

export type RegisterInput = z.infer<
  typeof registerSchema
>;

export type LoginInput = z.infer<
  typeof loginSchema
>;

export type VerifyEmailOtpInput = z.infer<
  typeof verifyEmailOtpSchema
>;

export type ResendEmailVerificationInput = z.infer<
  typeof resendEmailVerificationSchema
>;

export type ForgotPasswordInput = z.infer<
  typeof forgotPasswordSchema
>;

export type VerifyPasswordResetOtpInput = z.infer<
  typeof verifyPasswordResetOtpSchema
>;

export type ResetPasswordInput = z.infer<
  typeof resetPasswordSchema
>;

export type ChangePasswordInput = z.infer<
  typeof changePasswordSchema
>;

export type VerifyLoginOtpInput = z.infer<
  typeof verifyLoginOtpSchema
>;

export type VerifyOtpInput = z.infer<
  typeof verifyOtpSchema
>;